### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by pinobatch** [pinobatch/libbet#7]
It's been [suggested](http://gbdev.gg8.se/forums/viewtopic.php?pid=3468#p3468) to add achievements to the game, perhaps to help determine which ending is given. A few have been agreed upon:

- [x] debughex: In-game variable display
- [x] Detect "Completionist": Complete all 5 floors with 100%
- [x] Show earned achievements after game completion
- [x] Detect "Sink it": Reach 100% by moving to a dead end
- [x] Detect "Dash for the door": Reach 100% and move continuously to the exit without pausing or increasing Manhattan distance to the exit
- [x] Detect "Restless": Do not pause from the first move to the exit door. 100% not required
- [x] Detect "No scope": Press 360 degrees on the Control Pad in mid-air
- [x] Show achievement in status bar

Other achievements require more discussion:

- "Mind the frame": Press A+Up on the square below the exit door
- "Dizzy And The Boxing Gloves": "Keep rolling for X seconds straight"

**Comment by pinobatch** [comment]
"Restless" as originally defined by @ISSOtm turned out to be hard to earn, as he predicted. So I added a second easier achievement for not resting on a cell long enough to lift Libbet's head and not inputting any invalid moves: "No peeking".

- "Mind the frame" is A+Up below an _open_ exit door, as if jumping into the door frame.
- "Dizzy and..." is a Codemasters reference and implies that Libbet gets dizzy from continuously rolling. It'd probably be redundant to "Restless" anyway.

**Comment by ISSOtm** [comment]
If anything, "Restless" sounds impossible to get through pure skill, imo, since Libbet moves so quickly. If it's redundant over "Dizzy..." then I'd favor the latter.

**Comment by pinobatch** [comment]
I was able to do "Restless" in real time once, but only with debug options set to use the attract mode map whose route I had memorized. In the actual game, memorizing the map is probably impractical.

For now I've redefined it as leaving X tracks without hesitation. Start X at 12, and then tune it up or down. But an achievement an arbitrary threshold feels somehow less "pure" than one without one.

**Comment by ISSOtm** [comment]
Indeed. If the threshold is a round number or otherwise significant (eg. 42), the player may view it are more acceptable, I believe. Also they will probably figure that doing the "full" achievement would be too difficult - if they find the threshold to be sufficiently difficult (but not too much) to attain, I believe they will accept the arbitrary part of the goal.

**Comment by pinobatch** [comment]
One thing I tend to do when I'm indecisive about a game design is make it a build-time option. I managed to [`git gud`](https://github.com/fsufitch/git-gud) and earn hardcore Restless on random first floors without cheats twice: once on bgb and once on my GBC.
